// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String args[]) {
		int N = Integer.parseInt(args[0]);
		int countAbove = 0 , countBelow = 0 ;
		for (int i = 0; i < N ; i=i+1)
		{
			if (Math.random()>0.5) {
				countAbove = countAbove + 1;
			}
			else {
				countBelow = countBelow +1;
			}
		}
		System.out.println("> 0.5:  " + countAbove + " times");
		System.out.println("<= 0.5: " + countBelow + " times");
		if (countBelow != 0) { 
			if ((double)countAbove / countBelow==0) {
				System.out.println("Ratio:  " + countAbove / countBelow);
			} else {
			System.out.println("Ratio:  " + (double)countAbove / countBelow);
			}
		}
	
	}
}
